[secret_type]
name = "google_api_key"
regex = "AIza[0-9A-Za-z\\-_]{35}"
description = "Detects Google API keys"

examples = [
    "AIzaSyB-1234567890QWERTYUIOPSDFGHJKLZXCVB",
    "AIzaSyC-0987654321ASDFGHJKLQWERTYUIOZXCVB",
]

false_positives = []
