[secret_type]
name = "phone_number"
regex = "^\\+?(\\d{1,4})?[-.\\s]?\\(?\\d{1,4}\\)?[-.\\s]?\\d{1,9}[-.\\s]?\\d{1,9}$"
description = "Detects various formats of phone numbers including international and local formats."

examples = [
    "123-456-7890",
    "+1-123-456-7890",
    "+1 123 456 7890",
    "1234567890",
    "+11234567890",
]

false_positives = []
