[secret_type]
name = "redis_connection_string"
regex = "redis://(:?[:\\w]*@)?\\w+(:\\d+)?"
description = "Detects Redis connection strings"

examples = [
    "redis://user:password@localhost:6379",
    "redis://:password@localhost:6379",
    "redis://localhost:6379",
]

false_positives = []
