name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: linux
          - target: x86_64-pc-windows-gnu
            os: windows
          - target: x86_64-apple-darwin
            os: macos

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.target }}

    - name: Package
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release
        tar czvf ../../../minos-codex-${{ matrix.os }}.tar.gz minos-codex*
        cd -

    - name: Generate SHA256
      run: |
        cd target/${{ matrix.target }}/release
        sha256sum minos-codex* > ../../../minos-codex-${{ matrix.os }}.sha256
        cd -

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          minos-codex-${{ matrix.os }}.tar.gz
          minos-codex-${{ matrix.os }}.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

