name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Package
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release
        echo "Current directory:"
        pwd
        echo "Files available for packaging:"
        ls -l
        tar czvf ../../../minos-codex-${{ matrix.target }}-${{ matrix.os }}.tar.gz minos-codex* || echo "Tar command failed with exit code $?"
        echo "Check if tar.gz was created:"
        ls -l ../../../
        cd -

    - name: List Packaged Files
      run: ls -l target/${{ matrix.target }}/release/

    - name: Generate SHA256
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          shasum -a 256 minos-codex* > ../../../minos-codex-${{ matrix.target }}-${{ matrix.os }}.sha256
        else
          sha256sum minos-codex* > ../../../minos-codex-${{ matrix.target }}-${{ matrix.os }}.sha256
        fi
        cd -

    - name: List SHA256 Files
      run: ls -l target/${{ matrix.target }}/release/

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          minos-codex-${{ matrix.target }}-${{ matrix.os }}.tar.gz
          minos-codex-${{ matrix.target }}-${{ matrix.os }}.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
