name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Package
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release
        tar czvf ../../../minos-codex-${{ matrix.os }}.tar.gz minos-codex*
        cd -

    - name: Generate SHA256
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          shasum -a 256 minos-codex* > ../../../minos-codex-${{ matrix.os }}.sha256
        else
          sha256sum minos-codex* > ../../../minos-codex-${{ matrix.os }}.sha256
        fi
        cd -


    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/${{ matrix.target }}/release/minos-codex-${{ matrix.os }}.tar.gz
          target/${{ matrix.target }}/release/minos-codex-${{ matrix.os }}.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}